# Generated by Django 4.2.3 on 2023-07-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='testmonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('images', models.ImageField(upload_to='', verbose_name='profile photo')),
                ('desc', models.TextField(verbose_name='Your description')),
                ('name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'testmonial',
                'verbose_name_plural': 'Customer testmonial',
            },
        ),
    ]
